### ISSUE TITLE
ability to automatically collect information from EventEmitter

### ISSUE THREAD

**Issue by andrewrk** [backtrace-labs/backtrace-node#10]
Let's discuss an idea @sbahra had: monkey-patch `EventEmitter` (see [docs](https://nodejs.org/api/events.html)) to collect either a log or statistics about events.

This would probably be off by default - monkey-patching is serious business - but if users opted in to it, we could potentially give them a lot of insight into their application.

One concern is that EventEmitter is general purpose, potentially used extensively in "low-level" code, and this might generate quite a bit of noise. I think exploration and research is required to see if this can be useful.

**Comment by konraddysput** [comment]
hi @andrewrk 

I'm happy to announce today we added support for `EventEmitter`. Please check our latest changes and give us a feedback what do you think :)
