### ISSUE TITLE
Backtrace: multiple 'uncaughtException' listeners attached

### ISSUE THREAD

**Issue by sanoopjose** [backtrace-labs/backtrace-node#20]
Backtrace: multiple 'uncaughtException' listeners attached

I have tried backtrace-node in electron quick starter and getting this error.
https://github.com/electron/electron-quick-start.git

I have added this code in main.js

```
var backtrace = require('backtrace-node');

backtrace.initialize({
  endpoint: 'https://submit.backtrace.io/abc/token/json',
  token: 'token',
});
```

**Comment by konraddysput** [comment]
Hi @sanoopjose !
Your electron application probably use other `uncaughtException` listeners and `backtrace-node` library can't initialize `uncaughtException` listener. To disable this behavior and starts using `backtrace-node` without global exception handler please set `allowMultipleUncaughtExceptionListeners` to `true`

In your example:
```js
var backtrace = require('backtrace-node');

backtrace.initialize({
  endpoint: 'https://submit.backtrace.io/abc/token/json',
  token: 'token',
  allowMultipleUncaughtExceptionListeners: true,
});
```

**Comment by konraddysput** [comment]
Hi @sanoopjose !
Do you still have problems with `backtrace-node` library with my suggestions? 

Thanks!

**Comment by konraddysput** [comment]
Hi @sanoopjose!
I hope my suggestion works in your project. If you have any question feel free to ask here :) 

Thanks!
