### ISSUE TITLE
Uncaught exception report not sent on non-Windows

### ISSUE THREAD

**Issue by sarahedkins** [backtrace-labs/backtrace-node#23]
Uncaught exception reports (i.e. **not** manually triggered from a direct bt.report call) are not submitted to coroner on MacOS/Linux. Removing the below code snippet from `index.js` enables successful submission. @konraddysput - It looks like this is to have non-Windows apps collect memory info from the current process versus a child process. If that is not a requirement, we could remove this to fix. Otherwise, may need to dig deeper into why the direct `sendReport` call isn't working.

```
const execName = path.basename(process.execPath);
  if (execName !== 'node.exe') {
    sendReport(this.payload, err => {
      if (callback) {
        callback(err);
      } else if (err && debugBacktrace) {
        console.error(err.stack);
      }
    });
    return;
  }
```

**Comment by konraddysput** [comment]
Hey @sarahedkins,
We solved this issue in our last release. If you still have problems please let us know :)
