### ISSUE TITLE
node-machine-id can cause crashes

### ISSUE THREAD

**Issue by Mike-Bell** [backtrace-labs/backtrace-node#34]
as per this issue, `node-machine-id` can cause problems on certain machines due to permissions issues: https://github.com/automation-stack/node-machine-id/issues/56

This was made worse when this codebase changed from fetching the machine id during the report generation to fetching the machine id statically: https://github.com/backtrace-labs/backtrace-node/commit/48e3bdc44a1429f890d7cd2ff4eb4fcdb1d68a98#diff-19c5769b32e486be5464e2b259d16fd1217d53501e90ea7ed95b4dce09e7a40dR13

This essentially means that importing this library will cause the consuming app to immediately crash for some users

**Comment by sbahra** [comment]
Thank you for reporting this! We will work on a fix.

**Comment by Mike-Bell** [comment]
This is pretty easy to repro if you disable access to your registry. I used method 2 here https://www.top-password.com/blog/3-ways-to-disable-registry-editor-in-windows/

**Comment by sbahra** [comment]
@Mike-Bell We vendored in the library with a patch. How does it look for you now?

**Comment by sbahra** [comment]
We'll have a patch out next week, we have a fix in a personal branch for testing.

**Comment by konraddysput** [comment]
Hey @sbahra @Mike-Bell  

The new mechanism that we added to the backtrace-node@1.1.1 package should fix this issue. Thanks for sharing a lot of details with us @Mike-Bell. Please let us know if the newest version of the library doesn't help you. 

Pull request reference: https://github.com/backtrace-labs/backtrace-node/pull/37


Thanks!
