### ISSUE TITLE
Backtrace summed/unique event requests failing

### ISSUE THREAD

**Issue by twchapman** [backtrace-labs/backtrace-node#54]
We're getting a lot of these errors in our logs when running our app:

```
[2022-11-11 16:14:00.079] [error] Encountered error sending summed event: Request failed with status code 400
[2022-11-11 16:14:00.083] [error] Encountered error sending unique event: Request failed with status code 400
```

`backtrace-node` version `1.2.0`

----------------

We're not sure if these are important and messing up our stats, or if they're nothing to be concerned about, but they are appearing in our app launches frequently (maybe every time?). Is there something we need to change to fix this?

**Comment by konraddysput** [comment]
hey @twchapman 

I believe this might be because of the "application-specific" location for the package.json file. Do your reports have application.version attribute? If they don't - is there a way to set it via backtrace-client attributes? 

This should by default probably resolve the issue. However it would be great if we can solve it once forever, so any information about your project structure would be great!

**Comment by twchapman** [comment]
It looks like `application.version` is indeed `null`, which we noticed a while back, but I'm not sure why that is. We initialize backtrace like this:
```
 bt.initialize({
      endpoint: backtraceConfig.endpoint,
      token: backtraceConfig.token,
      disableGlobalHandler: true,
      attributes: {
         productName: app.name,
         companyName: strings.companyName,
         platform: process.platform,
         processType: 'main',
         version: getVersion(),
         channel: getChannel()
      }
   });
```
and the electron crash reporter like this:
```
crashReporter.start({
         productName: getAppName(),
         submitURL: `${backtraceConfig.endpoint}/post?format=minidump&token=${backtraceConfig.token}`,
         uploadToServer: true,
         globalExtra: {
            _companyName: strings.companyName,
            version: getVersion(),
            channel: getChannel()
         }
      });
```
Is there a different `version` attribute we should be setting somewhere to get `application.version` to work properly?

**Comment by konraddysput** [comment]
Can you pass attribute.version with application version to the backtrace client attributes in the initialize method?

**Comment by twchapman** [comment]
Hi, sorry for the delay, I've been out of the office. I went ahead and added `application.version` to the attributes, and will see if that resolves the issue over the next few weeks, then report back. Thanks!

**Comment by konraddysput** [comment]
@twchapman is this electron? Do you initialize your backtrace-integration in the renderer/main process?

**Comment by twchapman** [comment]
Sorry for not being clear! Yes, this is in Electron. We're seeing the error in our `main` log file; we initialize Backtrace in both places, the change I mentioned above was specifically for the `main` crash reporter.

**Comment by konraddysput** [comment]
@twchapman One sec - are you using backtrace-node in the renderer process or backtrace-js?

**Comment by twchapman** [comment]
We use `backtrace-node` in `main` and `backtrace-js` in `renderer`.

**Comment by konraddysput** [comment]
ok this might be the issue I guess in your setup. Is there any way you can generate a unique guid and add it as attribute to the backtrace-ndoe and backtrace-js constructor? 
```
 attributes: {
         productName: app.name,
         companyName: strings.companyName,
         platform: process.platform,
         processType: 'main',
         version: getVersion(),
         channel: getChannel(),
         'application.session': your-guid
      }
   }
```

**Comment by twchapman** [comment]
I could do that, should the GUID be the same on both sides?

**Comment by konraddysput** [comment]
Yes

**Comment by twchapman** [comment]
Got it, I'll give that a go. Thank you again!

**Comment by konraddysput** [comment]
Sorry for those issues. We already have a lot of ideas for improvements. I can promise the flow for electron should be much better really soon

**Comment by twchapman** [comment]
No worries, I'm looking forward to the changes. In the meantime, I added in the session GUID as well, and so far I haven't seen the errors in my logs, so that might have done the trick!

**Comment by konraddysput** [comment]
@twchapman thank you. I wil try to add you once again to the thread once we finish all the planned changes. Thanks

**Comment by twchapman** [comment]
Perfect, I'd appreciate that!
