### ISSUE TITLE
Add support for using Express

### ISSUE THREAD

**Issue by sbahra** [backtrace-labs/backtrace-node#6]
app.use(errorHandler)

**Comment by andrewrk** [comment]
Do you envision this feature automatically sending an error report? Or will this do something such as populate `request.backtraceReport` which you could then call `setError` on and `send`?

**Comment by sbahra** [comment]
Automatically, but I defer to your judgement. For prospective users, it would be very nifty if they just have to add one/two lines and they immediately get errors routed.
